### ISSUE TITLE
[object, Object] error in console.

### ISSUE THREAD

**Issue by menkzy** [SamShanks1/fivem-scenes#4]
Downloaded the built files fresh & tried to install to a server, but ended up getting this error.
`[    181281] [b2699_GTAProce]        CrBrowserMain/ [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] (@fivem-scenes/web/build/assets/index.c6985ead.js:47)`

After this, I downloaded the source files & compiled them, and still get this error.

It doesn't bring up the menu at all, and no other errors (server) are present

**Comment by SamShanks1** [comment]
I just downloaded a fresh install and the UI opened fine for me, the error is just a console.log which needed removing. Can I ask how you are trying to open the UI

**Comment by SamShanks1** [comment]
Sorted via discord
